FROM golang:1.9
COPY . /go/src/bitbucket.org/cmaiorano/golang-wol
WORKDIR /go/src/bitbucket.org/cmaiorano/golang-wol
RUN GOOS=linux go build -o golang-wol wolsrv.go

FROM scratch
COPY --from=0 /go/src/bitbucket.org/cmaiorano/golang-wol/golang-wol .
VOLUME /config
VOLUME /certs
EXPOSE 443 5000
ENTRYPOINT [ "./golang-wol" ]